[add]Record登録時にアニメーションを流すようにする
NUTFes/NUTMEG-Seeds pull request #171
Opened 2023-01-25 14:29 UTC by imaimai17468

ref #132
# 概要
レコードを追加したときに、おめでとうアニメーションを流すようにしました。

# 実装内容
- アニメーション用ボタンの作成(AnimationButton)
- おめでとうアニメーションを作成(RecordAddAnimation)
- apiについて、skillメソッドを使っているものをskillsに変更

# テスト項目

1. アニメーション実装のためにライブラリをいくつか入れたので、`docker compose run seeds_view npm install`でライブラリをインストールしてください。うまくいかない場合はBuildしなおしてみてください。(`make build` or `make rebuild`)
2. 適当にRecordを追加してください。
3. 花火のアニメーションが流れるか、文字が跳ねているか、ボタンのホバーじやクリック時のアニメーションが動作しているか確認してください。
4. 2つのボタンを押した時、ちゃんと遷移するか確認してください。

# 備考
花火アニメーションですが、録画しようとしたり、検証画面を開こうとすると、稀にパーティクルが消えず、花火無限生成編が始まって激重になるバグがあります。その場合はリロードしたらrecordsページに戻ります。
新しく追加したRecordに遷移するボタンですが、`router.push`の仕様なのか、なぜかrecordsに遷移してからrecords/[id]に遷移します。

2023-01-26 14:33 UTC, YushiroDodo63 commented on docker-compose.prod.yml
> +    image: nutmeg-seeds-seeds_api:latest
メモ：こっちの手元環境だと `image: nutmeg-seeds_seeds_api:latest` じゃないとcronのエラー出るんよなぁ... 
二川さんに教えた時も、 `image: nutmeg-seeds-seeds_api:latest` じゃないと動かなかったんで一旦ここはコメントだけしときます〜

2023-01-26 15:00 UTC, YushiroDodo63 requested changes
気になった点にコメント残しました！
基本的には大きな問題があるって感じではないです！
`route.push(record/id)` の部分に関しては俺も原因がよくわからないのとクリティカルではないかな？と思うので、一旦このままでOKです！

過去のPRレビューでも思ったのですが、 `console.log()` の消し忘れとか不要なファイルのpushとかがあるので、コミットする前（もしくはステージング前）に、その編集が適切かを確認するといいかもです＠

2023-01-26 16:19 UTC, imaimai17468 commented
修正完了しました！
あとアルティメット謎で、なぜかこのブランチに#164（スキルのカテゴリの追加・編集）の内容をpushしてしまったので、そちらのレビューもお願いできますか？

ref #164 
# 概要
スキルカテゴリを追加・編集できるようにしました。

# 実装内容
-フロントエンド
  - カテゴリ一覧ページ
  - 各カテゴリの詳細ページ
  - カテゴリ追加・編集・削除用モーダル
- バックエンド
  - カテゴリにも説明文が必要だと思ったので、detailカラムを追加 　

# テスト項目

1. Categoriesページに行き、seedデータである3つのカテゴリが表示されているか
2. カテゴリを追加できるか
3. 詳細ページが表示できるか
4. 詳細ページから、カテゴリの編集および削除ができるか

2023-02-09 09:56 UTC, YushiroDodo63 commented on view/next-project/src/components/common/AnimationButton/AnimationButton.tsx
> +export default RecordAddAnimation;
[0dbdd98](https://github.com/NUTFes/NUTMEG-Seeds/pull/171/commits/0dbdd989f779e9beb0de00fd5d9567790381fdb9) で対応しました

2023-02-09 10:15 UTC, YushiroDodo63 requested changes
@imaimai17468 
数カ所だけめっちゃ小さい修正お願いします！
５分もあれば終わるかと！
これが治ったら他は問題なさそうです！！

2023-02-09 10:15 UTC, YushiroDodo63 commented on view/next-project/src/components/common/CategoryEditModal.tsx
> +    const getRes = await get(getSkillDetailUrl);
この辺りの `skill` になっとるところは `catogory` に直しましょう！

2023-02-09 10:15 UTC, YushiroDodo63 commented on view/next-project/src/components/common/CategoryEditModal.tsx
> +          submitSkill(formData, query);
同上で、 `skill` を `catogory` に直しましょう！

2023-02-11 05:17 UTC, imaimai17468 commented on view/next-project/src/components/common/CategoryEditModal.tsx
> +    const getRes = await get(getSkillDetailUrl);
対応しました！（[9ece447](https://github.com/NUTFes/NUTMEG-Seeds/pull/171/commits/9ece447e9a1cca9796e422b4747b9abc5ae7a4e5)）

2023-02-11 05:17 UTC, imaimai17468 commented on view/next-project/src/components/common/CategoryEditModal.tsx
> +          submitSkill(formData, query);
対応しました！（[9ece447](https://github.com/NUTFes/NUTMEG-Seeds/pull/171/commits/9ece447e9a1cca9796e422b4747b9abc5ae7a4e5)）
（上と同じCommitです）

2023-02-11 05:30 UTC, merged