個人情報を編集できるようにする
NUTFes/NUTMEG-Seeds pull request #175
Opened 2023-02-27 05:17 UTC by imaimai17468

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

■    ■  ■    ■ ■■■■■■ ■    ■■  ■■■■■  ■■■■ 
■■   ■  ■    ■    ■   ■■   ■■  ■     ■■    
■■■  ■  ■    ■    ■   ■■  ■■■  ■     ■     
■ ■  ■  ■    ■    ■   ■ ■ ■ ■  ■■■■  ■     
■  ■ ■  ■    ■    ■   ■ ■ ■ ■  ■     ■  ■■■
■  ■ ■  ■    ■    ■   ■ ■■  ■  ■     ■    ■
■   ■■  ■■  ■     ■   ■  ■  ■  ■     ■■  ■■
■   ■■   ■■■■     ■   ■     ■  ■■■■■  ■■■■ 

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

resolve #165 

# WHY

- メンバーページから個人情報が変え放題
- 名前やメアド、パスワードなどのログイン情報が変えられない

# WAHT

- ヘッダーにプロフィールとログアウトできるメニューを追加
- プロフィールページで各種情報が変えれるように

# HOW

- React Hook Form導入
- Recoil導入
- localStorageをRecoilにリプレイス
- 名前・メアド変更フォーム実装
- パスワード変更フォーム実装
- プロフィール（学年課程）変更フォーム実装
- AuthProvider実装

# TEST

- [ ] サインインできるか
- [ ] サインアップできるか
- [ ] ヘッダーのMenuからログアウト・プロフィールページに移動できるか
- [ ] 名前とメールを変更できるか・それでログインできるか
- [ ] パスワードを変更できるか・それでログインできるか
- [ ] 学年や課程を変更できるか（メンバーページで確認）

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

  ■■■                  ■      
 ■                     ■      
 ■      ■■■   ■■■   ■■■■  ■■■ 
  ■■   ■  ■  ■  ■  ■  ■■  ■   
   ■■  ■■■■  ■■■■  ■   ■  ■■  
     ■ ■     ■     ■   ■    ■ 
 ■  ■■ ■     ■     ■  ■■    ■■
 ■■■■   ■■■   ■■■   ■■■■  ■■■ 

■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

2023-03-01 08:00 UTC, YushiroDodo63 requested changes
コメントした箇所の修正お願いします！
あと、追加でバグを複数箇所見つけたのでこの修正もお願いします！

- どのページでもリロードしたらログインページに飛ばされる。→ 何かしらでauthが吹っ飛んでる？
- passwordを更新するボタン、何も入力せずに一回クリックしても動作しない。2回目のクリックでやっとエラー文が出る

全部こうしろ！ってわけじゃないので、こうした方がいいでしょ！って箇所あったらSlackかGithubでコメントしてください 🙇‍♂️

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/components/common/PasswordResetForm/PasswordResetForm.tsx
> +          Profile Settings
`Update password` の方がいいかもです！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/components/common/SettingEditForm/SettingEditForm.tsx
> +          Profile Settings
`Update personal information` とか `Update personal settings` の方がいいかも！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx
> +          Profile Update
Update Profile の方がいいかも！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/components/common/HeaderMenu/HeaderMenu.tsx
> +import { userState } from 'src/store/user';
`@store/user` でimportできるように tsconfig を書き換えてくれたら嬉しいです！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/utils/api_methods.ts
> +export const get_with_token = async (url: string, currentUser: any) => {
すごい今更感あるけど、キャメルケースにした方がいいかもです！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/utils/api_methods.ts
> +export const put_with_token = async (url: string, data: any, currentUser: any) => {
これもキャメルケースにした方がいいかも！

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/context/AuthProvider.tsx
> +    if (userParams.userId !== '') {
ここのif文は userParams が undefined かどうかを確認したら大丈夫な気もするけど `userParams.userId` と比較して実装した理由ってあったりする？ 🤔

2023-03-01 08:00 UTC, YushiroDodo63 commented on view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx
> +}
フロントで使う時の型はキャメルケースの方がいいかも！

2023-03-02 16:15 UTC, imaimai17468 commented on view/next-project/src/context/AuthProvider.tsx
> +    if (userParams.userId !== '') {
localStorageにやってた時代にuser_idと比較していたので、その名残でそのまま実装しちゃいました！
userParamsがundefinedか確認するだけで良さそうなので、その方針に修正します！

2023-03-02 16:16 UTC, imaimai17468 commented on view/next-project/src/components/common/HeaderMenu/HeaderMenu.module.css
> +  color: black;
対応しました！([dd52da4](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/dd52da40b110900cd8410a83b776457f24cd6c02))

2023-03-02 16:17 UTC, imaimai17468 commented on view/next-project/src/components/common/HeaderMenu/HeaderMenu.tsx
> +        </div>
対応しました！（[12ef86f](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/12ef86faef54047d58c810ab32e0e217395637d7)）

2023-03-02 16:18 UTC, imaimai17468 commented on view/next-project/src/components/common/HeaderMenu/HeaderMenu.tsx
> +import { userState } from 'src/store/user';
対応しました！（[12ef86f](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/12ef86faef54047d58c810ab32e0e217395637d7) / [190677e](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/190677eda278077dccb00e1029f5b100c2284216)）

2023-03-02 16:18 UTC, imaimai17468 commented on view/next-project/src/utils/api_methods.ts
> +export const get_with_token = async (url: string, currentUser: any) => {
対応しました！（[6a92c9f](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/6a92c9fb50b743db4c41979458f2c08eafe7cb1b)）

2023-03-02 16:18 UTC, imaimai17468 commented on view/next-project/src/utils/api_methods.ts
> +export const put_with_token = async (url: string, data: any, currentUser: any) => {
対応しました！（[6a92c9f](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/6a92c9fb50b743db4c41979458f2c08eafe7cb1b)）

2023-03-02 16:19 UTC, imaimai17468 commented on view/next-project/src/context/AuthProvider.tsx
> +    if (userParams.userId !== '') {
対応しました！（[792d292](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/792d292aa539efae694c9c2354e32e10fb5a2e3a)）

2023-03-02 16:20 UTC, imaimai17468 commented on view/next-project/src/components/common/HeaderMenu/HeaderMenu.tsx
> +        </div>
[これ](https://github.com/NUTFes/NUTMEG-Seeds/pull/175#discussion_r1121227396)と同時にまとめて対応しちゃいました！（[12ef86f](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/12ef86faef54047d58c810ab32e0e217395637d7)）

2023-03-02 17:13 UTC, imaimai17468 commented on view/next-project/src/components/common/SettingEditForm/SettingEditForm.module.css
> +}
対応しました！
[d9a8b8a](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/d9a8b8a4ce2ee318573dd1d8d3789c28a43d8691)　[5d9ac41](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/5d9ac41789ee99f3350cd9c0445af60cc1adb7fe)

2023-03-02 17:13 UTC, imaimai17468 commented on view/next-project/src/pages/profile/index.tsx
> +          <h2 className={s.sub}>Edit Settings</h2>
対応しました！　[46f28f8](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/46f28f82644dbb82b8949b71926172fd8e44eaa6)

2023-03-02 17:14 UTC, imaimai17468 commented on view/next-project/src/components/common/SettingEditForm/SettingEditForm.tsx
> +export const SettingEditForm = (props: Props) => {
対応しました！　[af2cc03](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/af2cc034da01cc6d2f66284a1c6553706c1d3ebd)

2023-03-02 17:15 UTC, imaimai17468 commented on view/next-project/src/components/common/SettingEditForm/SettingEditForm.tsx
> +          Profile Settings
[これ](https://github.com/NUTFes/NUTMEG-Seeds/pull/175#discussion_r1121237156)と一緒に対応しました！

2023-03-02 17:15 UTC, imaimai17468 commented on view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx
> +          Profile Update
対応しました！　[d1d1448](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/d1d14487e85da8a52a8cdc7f70d982bc3fd74ce9)

2023-03-02 17:16 UTC, imaimai17468 commented on view/next-project/src/components/common/PasswordResetForm/PasswordResetForm.tsx
> +          Profile Settings
対応しました！　[f283bf6](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/f283bf69226506eaf3cb08945f9d123e50c7f7fc)

2023-03-02 17:25 UTC, imaimai17468 commented
@YushiroDodo63 

> 295001d

> どのページでもリロードしたらログインページに飛ばされる。→ 何かしらでauthが吹っ飛んでる？

修正しました

- userのstateのデフォルトが`undefined`ではなく`''`だった [85fba07](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/85fba0700f9f608789156272b345fd005d810c67) 
  - userStateの型にundefinedを追加
  - ログアウト時にundefinedを代入 
- 未ログイン時にログインページに飛ばす処理を`_app.tsx`で行っていた 
  - AuthProviderの内側でやらないとuserAuthのhooksが正常に動作しない？
  - 未ログインかどうかを見るだけのAuthLayout見たいのを作ろうか迷ったが、とりあえずAuthProviderに未ログイン時の処理を書いた [021b9c5](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/021b9c545d68db852eba7fa457801346d67c5619) [5b9fd08](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/5b9fd08c0dee938926e7fbb9a45a53d3940223f4)

> passwordを更新するボタン、何も入力せずに一回クリックしても動作しない。2回目のクリックでやっとエラー文が出る

修正しました

- エラーメッセージを表示するメソッドは書いていたが、submit時にエラーがある時に弾く処理を書いてなかった [295001d](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/295001da9fbaa0fc3a5555c73d65ddc59ce56ee2)

2023-03-06 07:56 UTC, imaimai17468 commented on view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx
> +}
対応しました！　[e560ee8](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/e560ee8e36b7131b62b5bca777a6876c72f08cf7)

2023-03-06 07:57 UTC, imaimai17468 commented on view/next-project/src/components/common/ProfileEditForm/ProfileEditForm.tsx
> +    };
一旦フロント側はキャメルケースで統一して、送信時にスネークケースに変換するようにしました！　[e560ee8](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/e560ee8e36b7131b62b5bca777a6876c72f08cf7)

また、objectのkeyをキャメルケース⇄スネークケースする関数を追加しました！　[350d804](https://github.com/NUTFes/NUTMEG-Seeds/pull/175/commits/350d804ee2a0e2db89483d2cbf1e7e594c8086af)

2023-03-14 11:15 UTC, YushiroDodo63 approved these changes
LGTM!!!

2023-03-14 11:15 UTC, merged